name: C/C++ CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make omp_to_img RESOLUTION=3840
    - uses: actions/upload-artifact@v3
      with:
        name: image
        path: ./image.jpeg
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: upload image to repo
